- hosts: all
  tasks:
    - name: dump_var
      debug:
        var: hostvars[inventory_hostname][item]
      when: >-
        not(
          item in (
            'groups',
            'module_setup',
            'omit',
            'playbook_dir'
          )
        ) and
        not(item | match("^ansible_")) and
        not(item | match("^inventory_"))
      with_items: "{{ hostvars[inventory_hostname] | sort }}"
